baseURL = "https://kaleabAlemayehu.github.io/"
title = "Kaleab Alemayehu"
theme = "matrix"
timeZone = "America/New_York"
summaryLength = 10
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[pagination]
pagerSize = 10

[markup]
[markup.highlight]
style = "tokyonight-night"
codeFences = true
guessSyntax = true
noClasses = true
lineNos = true
tabWidth = 4
[markup.goldmark.renderer]
unsafe = true
